---

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  #service_type: nodeport
  #nodeport_port: 30080

  service_type: clusterip
  ingress_type: ingress
  hostname: awx.tshr.it
  ingress_path: /

  #projects_persistence: true
  #projects_storage_access_mode: ReadWriteOnce
  postgres_configuration_secret: extdb-postgres-configuration
  #web_extra_volume_mounts: |
  #  - name: static-data
  #    mountPath: /var/lib/projects
  #extra_volumes: |
  #  - name: static-data
  #    persistentVolumeClaim:
  #      claimName: public-static-data-pvc
  extra_settings:
  # Required if we are serving http and we have a proxy that terminate httpS in front
  - setting: CSRF_TRUSTED_ORIGINS
    value:
      - https://awx.tshr.it
      - http://awx.tshr.it
      - https://git.tshr.it
      - http://git.tshr.it
