---
- name: Download the pandoc deb from the developers and install it
  tags: pandoc
  when: pandoc_install_from_pandoc_org
  block:
    - name: Get the pandoc deb package
      ansible.builtin.get_url:
        url: "{{ pandoc_pkg_url }}"
        dest: "/srv/{{ pandoc_pkg_file }}"
        mode: 0644

    - name: Install the pandoc deb package
      ansible.builtin.apt:
        deb: "/srv/{{ pandoc_pkg_file }}"

- name: Install pandoc from the distribution
  tags: pandoc
  when: not pandoc_install_from_pandoc_org
  block:
    - name: Install the pandoc deb package, distribution version
      ansible.builtin.apt:
        pkg: pandoc
        state: present
        cache_valid_time: 3600
