---

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:

    - name: Check if LXD network exist
       ansible.builtin.raw: "lxc network info {{ lxd_network }}"
      register: lxdbr_check
      failed_when: lxdbr_check not in [0, ]
      changed_when: false

    - name: Create the network if absent, cannot change it ATM
      ansible.builtin.raw: "lxc network create {{ lxd_network }} --type=bridge ipv4.address={{ lxd_subnet | ansible.utils.ipmath(254) }}/24 ipv4.nat=true"
      when: lxdbr_check != 0

    - include_tasks: lxd-containers.loop.yml
      loop: "{{ range(container_range_start, container_range_stop)|list }}"
      loop_control:
        loop_var: container
