---
- hosts: php

  vars_files:
    - vars.yml

  roles:
    - php_initial
    - php-mysql

  tasks:
    - name: Set php version
      shell:
        cmd: php --version | head -n 1 | awk '{print $2}' | cut -f1,2 -d'.'
      register: php_version
      changed_when: false
      check_mode: false
    
    - name: Create pools
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "/etc/php/{{ php_version.stdout }}/fpm/pool.d/{{ item.key }}.conf"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      loop: "{{ pool | dict2items }}"
      notify: restart php-fpm

    - name: Create www directory
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy our fancy server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php    
