---

apiVersion: v1
kind: Secret
metadata:
  name: extdb-postgres-configuration
  namespace: awx
stringData:
  host: "172.16.32.5"
  port: "5432"
  database: "awx"
  username: "awx_u"
  password: "{{ password }}"
  sslmode: allow
  type: unmanaged
type: Opaque

