---
# ansible-playbook -v -i inventory.yml -e @secrets.yml.enc --vault-password-file password_file install-db.yml

- hosts: db
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update system
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

- hosts: db
  gather_facts: yes
  become: true
  vars_files:
    - vars.yml

  roles:
    - ansible-role-postgresql
