download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/awx-awx-23.2.0.tar.gz
format_version: 1.0.0
name: awx
namespace: awx
server: https://galaxy.ansible.com/api/
signatures: []
version: 23.2.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/awx/awx/versions/23.2.0/
