download_url: https://galaxy.ansible.com/download/community-mysql-3.7.2.tar.gz
format_version: 1.0.0
name: mysql
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.7.2
version_url: https://galaxy.ansible.com/api/v2/collections/community/mysql/versions/3.7.2/
