---
- hosts: webservers

  vars_files:
    - vars.yml
  vars:
    - php_server: "{{ hostvars[groups['php'][ansible_play_hosts.index(inventory_hostname)]]['ansible_host']  }}"
    - php_fpm_port: 9000

  roles:
    - httpd_initial

  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Copy our fancy server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
      notify: restart apache2
    - name: Enable the proxy module
      command:
        argv:
          - a2enmod
          -  proxy_fcgi 
          -  setenvif
      notify: restart apache2
    - name: Copy the vhost configuration
      template:
        src: templates/vhosts.conf.j2
        dest: /etc/apache2/sites-available/vhosts.conf
      notify: restart apache2

