---
# ansible-playbook -v -i localhost, example-get-state.yml

- hosts: all
  gather_facts: yes
  become: no
  connection: local

  tasks:

    - name: Get Terraform EFS backend variables
      fetch_terraform_backend_outputs:
        object: "terraform.tfstate"
      register: tfstate
      no_log: true # Too much output

    - name: Print gathered information
      ansible.builtin.debug:
        var: tfstate

    - name: Print gathered information
      ansible.builtin.debug:
        var: tfstate.vars["aws_vpc-demoawx_vpc"]["cidr_block"]
