---
# ansible-playbook -v -i inventory.yml -e @secrets.yml.enc --vault-password-file password_file install-gitea.yml

- hosts: gitea
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update system
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: Add packages
      ansible.builtin.apt:
        pkg:
        - gnupg2

- hosts: gitea
  gather_facts: yes
  become: true
  vars_files:
    - vars.yml

  roles:
    - ansible-role-memcached
    - ansible-role-redis
    - ansible-role-gitea
    - ansible-role-nginx
