---
# ansible-playbook -v -i inventory.yml -e @secrets.yml.enc --vault-password-file password_file poweroff.yml

- hosts: k3s_cluster
  gather_facts: no
  become: yes

  tasks:
    - name: Unconditionally shutdown the cluster
      community.general.shutdown:
          delay: 30

