---
# ansible-playbook -v -i inventory.yml -e @secrets.yml.enc --vault-password-file password_file k3s-argocd-operator.yml
# https://github.com/ansible/argocd-operator/blob/devel/docs/installation/basic-install.md

- hosts: master[0]
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Add packages
      ansible.builtin.apt:
        pkg:
        - git
        - golang

    # - name: Clone the operator
    #   ansible.builtin.git:
    #     repo: https://github.com/argoproj-labs/argocd-operator.git
    #     dest: /srv/argocd-operator
    #     single_branch: yes
    #     version: "{{ argocd_operator_version }}"
    #     depth: 1
    #     accept_newhostkey: true
    #     clone: true
    #     force: true
    #
    # - copy:
    #     content: |2
    #       apiVersion: v1
    #       kind: ConfigMap
    #       metadata:
    #         name: argocd-demo
    #         namespace: argocd
    #         labels:
    #           app.kubernetes.io/name: argocd-demo
    #           app.kubernetes.io/part-of: argocd
    #       data:
    #           service_type: clusterip
    #           ingress_type: Route
    #     dest: /srv/argocd-operator/argocd-demo.yaml
    #
    # - copy:
    #     content: |2
    #       apiVersion: kustomize.config.k8s.io/v1beta1
    #       kind: Kustomization
    #       resources:
    #         - github.com/argoproj-labs/argocd-operator/config/default?ref={{ argocd_operator_version }}
    #         - argocd-demo.yaml
    #
    #       namespace: argocd-operator-system
    #
    #     dest: /srv/argocd-operator/kustomization.yaml
    #
    # - command: make deploy
    #   args:
    #     chdir: /srv/argocd-operator
    #
    # - command: kubectl apply -k /srv/argocd-operator
    #
    # - copy:
    #     content: |2
    #       ---
    #       apiVersion: argoproj.io/v1alpha1
    #       kind: ArgoCD
    #       metadata:
    #         name: argocd
    #         labels:
    #           tipo: ingress
    #       spec:
    #         server:
    #           grpc:
    #             ingress:
    #               enabled: true
    #           ingress:
    #             enabled: true
    #           insecure: true
    #     dest: /srv/k8s-charts/argocd.yaml

    - name: Create argocd namespace
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Download manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /srv/k8s-charts/argocd-install.yaml
        mode: '0644'

    - name: Create argocd
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        namespace: argocd
        state: present
        src: /srv/k8s-charts/argocd-install.yaml
